stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: |-
        echo hello
        exit 1
notification:
  recipients:
    - notifier: myslack
      recipient: "#mon_demo"
    - notifier: myslack
  condition:
  - Failed
